> data <- read.table(file, header = TRUE, sep = ";", stringsAsFactors = FALSE, dec = ".")
> subSetData <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
> globalActivePower <- as.numeric(subSetData$Global_active_power)
> total_data <- length(subSetData$Global_active_power)
> par(mfrow = c(2, 2))
> plot(1:total_data, as.numeric(subSetData$Global_active_power), type = "l", col = "black", xaxt = "n", xlab = "", ylab = "Global Active Power") axis(side = 1, at = c(1, total_data/2, total_data), labels = c("Thu", "Fri", "Sat"))
> plot(1:total_data, as.numeric(subSetData$Global_active_power), type = "l", col = "black", xaxt = "n", xlab = "", ylab = "Global Active Power")
> axis(side = 1, at = c(1, total_data/2, total_data), labels = c("Thu", "Fri", "Sat"))
> plot(1:total_data, as.numeric(subSetData$Voltage), type = "l", col = "black", xaxt = "n", xlab = "datetime", ylab = "Voltage")
> axis(side = 1, at = c(1, total_data/2, total_data), labels = c("Thu", "Fri", "Sat"))
> plot(1:total_data, as.numeric(subSetData$Sub_metering_1), type = "l", col = "black", xaxt = "n", xlab = "", ylab = "Energy sub metering")
> lines(1:total_data, as.numeric(subSetData$Sub_metering_2), col = "red")
> lines(1:total_data, as.numeric(subSetData$Sub_metering_3), col = "blue")
> axis(side = 1, at = c(1, total_data/2, total_data), labels = c("Thu", "Fri", "Sat"))
> legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, bty = "n")
> plot(1:total_data, as.numeric(subSetData$Global_reactive_power), type = "l", col = "black", xaxt = "n", xlab = "datetime", ylab = "Global_reactive_power")
> axis(side = 1, at = c(1, total_data/2, total_data), labels = c("Thu", "Fri", "Sat"))
